### ISSUE TITLE
Docker image no longer published

### ISSUE THREAD

**Issue by nwithan8** [fscorrupt/docker-arrs2discord#1]
Seems like the image is no longer available in GHCR: ghcr.io/fscorrupt/docker-arrs2discord:latest

**Comment by fscorrupt** [comment]
now?

**Comment by nwithan8** [comment]
Nope

**Comment by fscorrupt** [comment]
Okey, container rebuild triggered, it now got updated.

**Comment by nwithan8** [comment]
Hmm, I see in the logs of the Action that it got pushed, but the link to the page for it still doesn't resolve. I wonder if there's some setting in this repo that is disabling public access to the Packages tab (GHCR)

**Comment by fscorrupt** [comment]
Youre right, it was at private, changed to public now!
